services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001" 
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/note-taking-app 
    volumes:
      - ./backend:/app 
    env_file:
      - ./backend/.env 
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3002:80" 
    volumes:
      - ./frontend:/app
   
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network

volumes:
  mongo-data: 

networks:
  app-network: 
    driver: bridge 